name: EnchantmentInfo
main: EnchantmentInfo\EnchantmentInfo
author: PedsHampton
version: 5.0.0
api: [3.0.0, 3.5.3, 3.5.4, 3.5.5]
commands:
  enchantmentinfo:
    aliases: [enchantinfo, einfo, enchinfo]
    description: Checks Info On A Enchantment Using EnchantmentInfo
