name: EnchantmentInfo
main: EnchantmentInfo\EnchantmentInfo
author: PedsHampton
version: 4.0.0
api: [3.0.0, 3.5.3]
commands:
  enchantmentinfo:
    aliases: [enchantinfo, einfo, enchinfo]
    description: Checks Info On A Enchantment Using EnchantmentInfo
