name: EnchantmentInfo
main: EnchantmentInfo\EnchantmentInfo
author: PedsHampton
version: 3.0.0
api: [3.0.0]
commands:
  enchantmentinfo:
    aliases: [enchantinfo, einfo, enchinfo]
    description: Checks Info On A Enchantment Using EnchantmentInfo
